# GitHub Action for generating a contribution graph with a snake eating your contributions.

name: Generate Animation

on:
  # run automatically every 24 hours
  schedule:
    - cron: "0 0 * * *" 
    
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Generate Snake
        uses: Platane/snk@v3
        id: snake-animation
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: |
            ./assets/github-contribution-grid-snake.gif
            ./assets/github-contribution-grid-snake.svg
            ./assets/github-contribution-grid-snake-dark.svg?palette=github-dark
        env:
          # a github token is required to fetch the contribution calendar from github API
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}    
          
      - name: Push to GitHub
        uses: EndBug/add-and-commit@v9
        with:
          add: 'assets'
          default_author: github_actions
          message: 'Generate Github contribution heatmap animation'